### ISSUE TITLE
Use with resource packs using core vanilla shaders result in a completely black screen.

### ISSUE THREAD

**Issue by Duranson1** [SteamworkMC/Seaborgium#1]
![2023-04-29_12 29 15](https://user-images.githubusercontent.com/88769753/235320985-a70e17ad-b1f0-4d8a-a7c2-00a10f091b52.png)

**Comment by UndefinedBHVR** [comment]
I'll go ahead and work on a patch for this. Thank you for letting me know.

**Comment by UndefinedBHVR** [comment]
The issue should be resolved with version 0.1.1 on Modrinth @Duranson1 please let me know if it worked.

**Comment by Duranson1** [comment]
Unfortunately still experiencing the same issue with 0.1.1.

**Comment by UndefinedBHVR** [comment]
Can you provide me the name of the resource pack causing this to happen?

**Comment by Duranson1** [comment]
Yeah, I'm using vanillatweaks warm glow, wavy leaves and wavy plants resource packs.

**Comment by UndefinedBHVR** [comment]
I'm unable to replicate the issue. Can I get a list of mods. Are you using Iris by chance with a shader through iris loaded?

**Comment by Duranson1** [comment]
Not using Iris or Sodium, but yeah it could definitely be a conflict of mods. I will try with only seaborgium and see if the issue is still there

**Comment by Duranson1** [comment]
Yeah, just checked and I still have the issue when only running Seaborgium.

**Comment by UndefinedBHVR** [comment]
How unusual. I'm entirely unable to replicate it. I'll keep working on this and see if I can figure it out.

**Comment by Duranson1** [comment]
Huh, really weird. If you want I could upload the exact resource pack that I'm using here, there are a couple other vanillatweaks features in it that aren't shader-related but could be causing it, no clue though.

**Comment by UndefinedBHVR** [comment]
Go ahead and post it, I'll take a look when I get the chance.

**Comment by Duranson1** [comment]
[VanillaTweaks_r506614.zip](https://github.com/SteamworkMC/Seaborgium/files/11362291/VanillaTweaks_r506614.zip)

**Comment by UndefinedBHVR** [comment]
@Duranson1 I managed to replicate it, only appears for me when the game is launched with it already enabled, if you reload the resource pack in game it fixes itself.

**Comment by UndefinedBHVR** [comment]
Fixed with release [#0.1.2](https://modrinth.com/mod/seaborgium/version/0.1.2)
