### ISSUE TITLE
Bug using Xaero's World Map

### ISSUE THREAD

**Issue by Temmpou** [SteamworkMC/Seaborgium#18]
When Seaborgium is enabled, opening the world map does not render the map at all. This works fine with Seaborgium disabled.
![seaborgium](https://user-images.githubusercontent.com/58180179/236826734-d7732042-2cda-45a6-bffc-ec8e099e0d52.png)

**Comment by UndefinedBHVR** [comment]
I'm unable to replicate this issue, can you provide me with more details about your game?

- What version of the mod you're running
- What version of minecraft you're on
- A list of the currently enabled mods
- Whether or not you're using Optifine

**Comment by MrFastZombie** [comment]
I'm having the same issue.

Without Seaborgium:
![2023-05-08_20 04 25](https://user-images.githubusercontent.com/18253497/236968745-8bc92f46-22de-4c95-aec9-23a490f78850.png)

With:
![2023-05-08_20 06 00](https://user-images.githubusercontent.com/18253497/236968759-33d8a56a-32a3-4bee-9407-bb162072fc64.png)

I'm using seaborgium-mc1.18.2-0.1.3b. 
Forge 40.2.0
No optifine.

<details>
  <summary>Mod list</summary>
  
  [✔] almostunified-forge-1.18.2-0.3.10
  [✔] architectury-4.11.93-forge
  [✔] AttributeFix-Forge-1.18.2-14.0.2
  [✔] AutoRegLib-1.7-53
  [✔] balm-3.2.6
  [✔] BetterModsButton-v3.2.3-1.18.2-Forge
  [✔] canary-mc1.18.2-0.1.7
  [✔] catalogue-1.6.2-1.18.2
  [✔] citadel-1.11.3-1.18.2
  [✔] cloth-config-6.4.90-forge
  [✔] Clumps-forge-1.18.2-8.0.0+17
  [✔] cofh_core-1.18.2-9.2.1.39
  [✔] configured-2.0.1-1.18.2
  [✔] Continents_1.18.2_v1.1.2
  [✔] Controlling-forge-1.18.2-9.0+22
  [✔] CraftTweaker-forge-1.18.2-9.1.207
  [✔] create-1.18.2-0.5.0.i
  [✔] CreateTweaker-1.18.2-2.0.0.18
  [✔] CreativeCore_FORGE_v2.6.16_mc1.18.2
  [✔] Ding-1.18.2-Forge-1.4.0
  [✔] DistantHorizons-1.6.5a-1.18.2
  [✔] dtterralith-1.18.2-Alpha3
  [✔] dynamiccrosshair-5.1+1.18.2-forge
  [✔] DynamicTrees-1.18.2-1.0.2
  [✔] entityculling-forge-1.6.1-mc1.18.2
  [✔] ferritecore-4.2.2-forge
  [✔] flywheel-forge-1.18.2-0.6.8.a
  [✔] ftb-industrial-contraptions-1802.1.6-build.220
  [✔] ftb-library-forge-1802.3.11-build.177
  [✔] iceandfire-2.1.12-1.18.2-beta2
  [✔] ImmersiveEngineering-1.18.2-8.4.0-161
  [✔] ImmersivePetroleum-1.18.2-4.1.0-19
  [✔] Jade-1.18.2-forge-5.2.6
  [✔] JAOPCA-1.18.2-4.1.15.28
  [✔] jei-1.18.2-forge-10.2.1.1004
  [✔] JustEnoughResources-1.18.2-0.14.2.206
  [✔] kubejs-create-forge-1802.2.2-build.28
  [✔] kubejs-forge-1802.5.5-build.569
  [✔] kubejs-thermal-1802.1.5-build.16
  [✔] lazydfu-1.0-1.18+
  [✔] Mantle-1.18.2-1.9.45
  [✔] modernfix-mc1.18.2-forge-2.5.1
  [✔] MouseTweaks-forge-mc1.18-2.21
  [✔] Placebo-1.18.2-6.6.7
  [✔] pluto-mc1.18.2-0.0.6
  [✔] rhino-forge-1802.2.1-build.255
  [✔] rubidium-0.5.6
  [✔] saturn-mc1.18.2-0.0.4
  [✔] seaborgium-mc1.18.2-0.1.3b
  [✔] selene-1.18.2-1.17.9
  [✔] shutupexperimentalsettings-1.0.5
  [✔] smoothchunk-1.18.2-1.9
  [✔] spark-1.10.38-forge
  [✔] Terralith_v2.2.3
  [✔] The_Undergarden-1.18.2-0.7.1
  [✔] thermal_cultivation-1.18.2-9.2.0.16
  [✔] thermal_dynamics-1.18.2-9.2.1b.13
  [✔] thermal_expansion-1.18.2-9.2.0.20
  [✔] thermal_foundation-1.18.2-9.2.0.46
  [✔] thermal_innovation-1.18.2-9.2.0.17
  [✔] thermal_integration-1.18.2-9.2.0.16
  [✔] thermal_locomotion-1.18.2-9.2.0.13
  [✔] Visuality-0.6+forge-mc1.18.2
  [✔] Xaeros_Minimap_23.4.1_Forge_1.18.2
  [✔] XaerosWorldMap_1.30.1_Forge_1.18.2
  
</details>

I tried testing it with just Xaero's & Seaborgium installed, and it works fine for me like that as well. So I'm guessing another mod is interfering somehow

**Comment by UndefinedBHVR** [comment]
With this modlist I might have a couple of theories, I'll see if I can figure it out over the next week or so. For now, can you tell me what happens when you run `/sbx invalidate`? Does that resolve the issue? Or does it continue to happen?

**Comment by MrFastZombie** [comment]
Still happens if I run `/sbx invalidate`.

**Comment by ullebe1** [comment]
I can also replicate this.

<details>

<summary>Mods</summary>

```
  [✔] AI-Improvements-1.18.2-0.5.2
  [✔] appleskin-forge-mc1.18.2-2.4.1
  [✔] architectury-4.11.93-forge
  [✔] badpackets-forge-0.1.3
  [✔] balm-3.2.6
  [✔] better-loading-screen-1.4.0
  [✔] betterbiomeblend-1.18.2-1.3.5-forge
  [✔] BetterF3-3.0.0-Forge-1.18.2
  [✔] BetterPingDisplay-1.18.2-1.1
  [✔] canary-mc1.18.2-0.1.8
  [✔] cloth-config-6.3.81-forge
  [✔] controllable-0.17.0-1.18.2
  [✔] create-1.18.2-0.5.0.i
  [✔] debugify-1.11.0-forge-1.18.2
  [✔] dynamiclightsreforged-1.18.2_v1.3.3
  [✔] entityculling-forge-1.6.1-mc1.18.2
  [✔] farsight-1.18.2-1.9
  [✔] ferritecore-4.2.2-forge
  [✔] flywheel-forge-1.18.2-0.6.8.a
  [✔] GameMenuModOption-1.18-Forge-1.14.2
  [✔] jei-1.18.2-forge-10.2.1.1002
  [✔] lazydfu-1.0-1.18+
  [✔] light-overlay-6.0.5-forge
  [✔] lightspeed-1.18.2-1.0.2
  [✔] modernfix-mc1.18.2-forge-2.5.2
  [✔] netherportalfix-forge-1.18.2-9.0.1
  [✔] NoChatLagForge-1.1.0-1.17-1.18
  [✔] oculus-1.5.2
  [✔] oculus-flywheel-compat-1.18.2-0.1.8-BETA
  [✔] pluto-mc1.18.2-0.0.6
  [✔] preciseblockplacing-1.1.0+1.18.2-forge
  [✔] rubidium_extras-1.18.2_v1.3.2
  [✔] rubidium-0.5.6
  [✔] saturn-mc1.18.2-0.0.4
  [✔] seaborgium-mc1.18.2-0.1.3b
  [✔] starlight-1.0.2+forge.546ae87
  [✔] wthit-forge-4.13.6
  [✔] Xaeros_Minimap_FP23.4.0_Forge_1.18.2
  [✔] XaerosWorldMap_1.30.2_Forge_1.18.2
```

</details>

If you'd like to try with my setup, you can find the Packwiz config [here](https://ullebe1.github.io/tk-gaming-mc-modpack/pack.toml) and the source [here](https://github.com/ullebe1/tk-gaming-mc-modpack).

**Comment by mrGRINCH** [comment]
> With: ![2023-05-08_20 06 00](https://user-images.githubusercontent.com/18253497/236968759-33d8a56a-32a3-4bee-9407-bb162072fc64.png)

I'm also having the exact same issue as MrFastZombie.

I was also having my FPS drop to 0 when I went to a certain area but was perfectly fine elsewhere.

Both issues were solved after removing Seaborgium.

I spent a long time testing all the mods and solved it once removing Seaborgium.

<details>
<summary>Mods</summary>
<br>
  [✔] advancements_tracker_1.18.2-1.6.1
  [✔] AE2-Things-1.0.5
  [✔] AkashicTome-1.5-20
  [✔] alexsmobs-1.18.6
  [✔] appleskin-forge-mc1.18.2-2.4.1
  [✔] appliedenergistics2-forge-11.7.0
  [✔] Architects-Palette-1.18.2-1.2.0
  [✔] architectury-4.10.88-forge
  [✔] autoreconnect-forge-2.0.0
  [✔] AutoRegLib-1.7-53
  [✔] auudio_forge_1.0.3_MC_1.18-1.18.2
  [✔] auxiliaryblocks-1.18.2-0.4.1
  [✔] balm-3.2.1+0
  [✔] baritone-api-forge-1.8.4
  [✔] bdlib-1.19.3.7-mc1.18.2
  [✔] BetterAdvancements-1.18.2-0.2.0.146
  [✔] betterbiomeblend-1.18.2-1.3.5-forge
  [✔] BetterCompatibilityChecker-1.1.21-build.48+mc1.18.2
  [✔] BetterF3-3.0.0-Forge-1.18.2
  [✔] betterfpsdist-1.18.2-1.5
  [✔] BetterModsButton-v3.2.3-1.18.2-Forge
  [✔] BetterPingDisplay-1.18.2-1.1
  [✔] blockcarpentry-1.18-0.3.0
  [✔] Bookshelf-Forge-1.18.2-13.2.51
  [✔] Botania-1.18.2-435
  [✔] BotanyPots-Forge-1.18.2-8.0.23
  [✔] buildinggadgets-3.13.2-build.21+mc1.18.2
  [✔] cagerium-1.18.2-1.1.6
  [✔] camera-1.18.2-1.0.5
  [✔] canary-mc1.18.2-0.2.3
  [✔] catalogue-1.6.2-1.18.2
  [✔] cfm-7.0.0-pre35-1.18.2
  [✔] citadel-1.11.3-1.18.2
  [✔] cloth-config-6.2.62-forge
  [✔] Clumps-forge-1.18.2-8.0.0+17
  [✔] cofh_core-1.18.2-9.1.2.32
  [✔] collective-1.18.2-6.59
  [✔] ColossalChests-1.18.2-1.8.3
  [✔] comforts-forge-1.18.2-5.0.0.5
  [✔] Compressium-1.4.2-build.9+mc1.18.2
  [✔] configured-2.0.1-1.18.2
  [✔] connectedness-1.18.2-2.0.1a
  [✔] Controlling-forge-1.18.2-9.0+22
  [✔] cookingforblockheads-forge-1.18.2-12.2.0
  [✔] CoordinatesDisplay-2.1.1
  [✔] corpse-1.18.2-1.0.2
  [✔] craftingtweaks-forge-1.18.2-14.0.3
  [✔] CraftTweaker-forge-1.18.2-9.1.206
  [✔] create-1.18.2-0.5.0.i
  [✔] CreateTweaker-1.18.2-2.0.0.18
  [✔] Cucumber-1.18.2-5.1.3
  [✔] curios-forge-1.18.2-5.0.9.0
  [✔] CyclopsCore-1.18.2-1.16.1
  [✔] DarkUtilities-Forge-1.18.2-10.0.5
  [✔] Decorative Blocks-forge-1.18.2-2.1.2
  [✔] drawerfps-1.18.2-2.4
  [✔] DrawersTooltip-1.18.2-forge-5.0.0
  [✔] drippyloadingscreen_forge_1.6.6_MC_1.18-1.18.2
  [✔] EasierVillagerTrading-forge-1.18.2-1.0.0
  [✔] easy_piglins-1.18.2-1.0.4
  [✔] easy_villagers-1.18.2-1.0.11
  [✔] ecologics-forge-1.18.2-1.7.11
  [✔] elevatorid-1.18.2-1.8.4
  [✔] enercell-1.18.2-1.0.2
  [✔] Entity_Collision_FPS_Fix-forge-1.18.2-1.0.0
  [✔] entityculling-forge-1.6.1-mc1.18.2
  [✔] EquipmentCompare-1.18.2-forge-1.3.3
  [✔] everycomp-1.18.2-1.5.15
  [✔] extremesoundmuffler-3.30_forge-1.18.2
  [✔] fairylights-5.0.0-1.18.2
  [✔] Fastload-Reforged-8.2.1-+1.18.2
  [✔] FastWorkbench-1.18.2-6.0.2
  [✔] ferritecore-4.2.2-forge
  [✔] FluxNetworks-1.18.2-7.0.8.12
  [✔] flywheel-forge-1.18.2-0.6.8.a
  [✔] framedcompactdrawers-1.18-4.1.0
  [✔] fullbrightnesstoggle-1.18.2-3.0
  [✔] GameMenuModOption-1.18-Forge-1.14.2
  [✔] hidehands-1.18.2-4.0
  [✔] Highlighter-1.18.1-1.1.2
  [✔] Iceberg-1.18.2-forge-1.0.49
  [✔] ImmediatelyFastReforged-1.18.2-1.1.10
  [✔] InitialInventory-forge-1.18.2-6.0.8
  [✔] inventoryessentials-forge-1.18.2-4.0.3
  [✔] invhud.forge.1.18.2-3.4.12
  [✔] ironfurnaces-1.18.2-3.3.3
  [✔] IronGenerators-2.0.2-1.18.2
  [✔] ispawner-1.1.5-forge
  [✔] Jade-1.18.2-forge-5.2.6
  [✔] jei-1.18.2-9.7.2.1001
  [✔] JEITweaker-1.18.2-3.0.0.9
  [✔] JustEnoughResources-1.18.2-0.14.1.171
  [✔] keywizard-forge-2.0.1-1.18.2
  [✔] konkrete_forge_1.6.0_MC_1.18-1.18.2
  [✔] kotlinforforge-3.12.0-all
  [✔] lazydfu-1.0-1.18+
  [✔] LegendaryTooltips-1.18.2-1.3.1
  [✔] libnonymous-2.1.0
  [✔] lightspeed-1.18.2-1.0.2
  [✔] lootbeams-1.18.1-release-july1722
  [✔] Mantle-1.18.2-1.9.31
  [✔] mcjtylib-1.18-6.0.20
  [✔] mcw-bridges-2.0.6-mc1.18.2forge
  [✔] mcw-doors-1.0.7-mc1.18.2
  [✔] mcw-fences-1.0.7-mc1.18.2forge
  [✔] mcw-furniture-3.0.2-mc1.18.2
  [✔] mcw-lights-1.0.4-mc1.18.2
  [✔] mcw-trapdoors-1.0.8-mc1.18.2forge
  [✔] mcw-windows-2.1.1-mc1.18.2forge
  [✔] Mekanism-1.18.2-10.2.5.465
  [✔] MekanismGenerators-1.18.2-10.2.5.465
  [✔] merequester-1.18.2-1.0.3
  [✔] MiningCoolDownFixForge-1.2
  [✔] mininggadgets-1.11.1
  [✔] MmmMmmMmmMmm-1.18.2-1.5.2
  [✔] modernfix-forge-5.0.2+mc1.18.2
  [✔] modular-routers-1.18.2-9.1.1-93
  [✔] MouseTweaks-forge-mc1.18-2.21
  [✔] NaturesCompass-1.18.2-1.9.7-forge
  [✔] neoncraft2-2.2
  [✔] NoFog-1.3.2+1.18.2-forge
  [✔] okzoomer-forge-1.18.2-1.1.1
  [✔] OpenLoader-Forge-1.18.2-12.0.1
  [✔] PackMenu-1.18.2-4.1.3
  [✔] Patchouli-1.18.2-71.1
  [✔] PickUpNotifier-v3.2.1-1.18.2-Forge
  [✔] PigPen-Forge-1.18.2-8.0.1
  [✔] Ping-1.18-1.8.0
  [✔] pipez-1.18.2-1.1.5
  [✔] Placebo-1.18.2-6.2.0
  [✔] pluto-mc1.18.2-0.0.6
  [✔] polymorph-forge-1.18.2-0.46
  [✔] Powah-3.0.7
  [✔] Prism-1.18.2-1.0.1
  [✔] PuzzlesLib-v3.3.5-1.18.2-Forge
  [✔] Quark-3.2-358
  [✔] ReAuth-1.18-Forge-4.0.6
  [✔] rebind_narrator-forge-1.18.2-2.0.0
  [✔] refinedstorage-1.10.4
  [✔] refinedstorageaddons-0.8.2
  [✔] reforgium-1.18.2-1.0.12a
  [✔] rftoolsbase-1.18-3.0.11
  [✔] rottencreatures-forge-1.18.2-1.0.0
  [✔] rsrequestify-2.2.0
  [✔] rubidium_extras-1.18.2_v1.3.2
  [✔] rubidium-0.5.5
  [✔] rubidium-extra-0.4.18+mc1.18.2-build.86
  [✔] Runelic-Forge-1.18.2-11.0.1
  [✔] saturn-mc1.18.2-0.0.4
  [✔] ScalableCatsForce-2.13.10-build-12-with-library
  [✔] selene-1.18.2-1.17.9
  [✔] serverconfigupdater-2.2
  [✔] shetiphiancore-1.18-3.10.12
  [✔] shutupexperimentalsettings-1.0.5
  [✔] SimpleStorageNetwork-1.18.2-1.6.2
  [✔] simplylight-1.18.2-1.4.5-build.43
  [✔] smoothboot(reloaded)-mc1.18.2-0.0.2
  [✔] Snad-1.18.2-1.22.04.15a
  [✔] sophisticatedbackpacks-1.18.2-3.18.46.821
  [✔] sophisticatedbackpacksvh-1.18.2-1.0.5.13
  [✔] sophisticatedcore-1.18.2-0.5.48.244
  [✔] spark-1.10.38-forge
  [✔] starlight-1.0.2+forge.546ae87
  [✔] StorageDrawers-1.18.2-10.2.1
  [✔] supermartijn642configlib-1.1.6-forge-mc1.18
  [✔] supermartijn642corelib-1.0.19-forge-mc1.18
  [✔] supplementaries-1.18.2-1.5.14
  [✔] TerraBlender-forge-1.18.2-1.2.0.126
  [✔] Terralith_v2.2.3
  [✔] TextruesRubidiumOptions-1.0.5-mc1.18.2
  [✔] the_vault-1.18.2-3.8.0.2246
  [✔] thermal_expansion-1.18.2-9.1.0.18
  [✔] thermal_foundation-1.18.2-9.1.0.34
  [✔] titanium-1.18.2-3.5.8-40
  [✔] torchmaster-18.1.0
  [✔] torohealth-1.18-forge-2
  [✔] trashcans-1.0.15-forge-mc1.18
  [✔] twigs-1.1.4-patch4+1.18.2-forge
  [✔] vaultintegrations-1.18.2-1.0.10
  [✔] Waddles-1.18.2-0.8.19
  [✔] waystones-forge-1.18.2-10.1.0
  [✔] weirdinggadget-1.18.1-2.2.11
  [✔] Xaeros_Minimap_22.17.0_Forge_1.18.2
  [✔] XaerosWorldMap_1.28.7_Forge_1.18.2
  [✔] xnet-1.18-4.0.7
  </details>
