### ISSUE TITLE
[Discussion] Uploading to CurseForge?

### ISSUE THREAD

**Issue by Kasualix** [SteamworkMC/Seaborgium#19]
### What feature?

Can you upload Seaborgium on CurseForge?

### Give us more details.

N/A

**Comment by UndefinedBHVR** [comment]
Sorry, at the current time, I don't plan to upload anything to CurseForge. Aside from the obvious of Modrinth being a superior platform, CurseForge is owned by Overwolf who I have a long personal history with and refuse to interact nor associate with at all.

Apologies. If Overwolf/Curse stops their anti-developer practices and improves the platform, I'll reconsider. However, for now. No.

I'll go ahead recategorize this to a discussion, others are free to put in their own input. Please keep it civil however.

**Comment by Kasualix** [comment]
I do think Modrinth is a superior platform too ~and CurseForge is indeed a piece of shit in many aspects~, but it's still a long way off until it grows and enough people use it to be as much as CurseForge.

**Comment by Trickster-4** [comment]
ok but why did you deleted the modrinth page as well?

**Comment by Kasualix** [comment]
> ok but why did you deleted the modrinth page as well?

https://github.com/SteamworkMC/Seaborgium/issues/23#issuecomment-1716171939
