### ISSUE TITLE
[Bug]: Rendering Conflict with InventoryHUD+

### ISSUE THREAD

**Issue by bonkmaykr** [SteamworkMC/Seaborgium#20]
### Version information

seaborgium-mc1.19.4-0.1.3

### Expected Behavior

InventoryHUD+'s effects should draw on top of the health meter like they do normally.

### Actual Behavior

Artwork for effects shown from InventoryHUD+ will render correctly, but any effect timer text rendering above absorption hearts will be invisible wherever there is an overlap.

### Reproduction Steps

1. Install InventoryHUD+, then install Seaborgium
2. Place your effects HUD above your hotbar so extra health will move up underneath it.
3. run `/effect give @s minecraft:absorption infinite 200` or something similar
4. Run a few other /effect commands to give yourself other effects if the HUD isn't overlapping yet

### Java version

Java 17.0.4

### CPU

Intel Core i5-8400

### GPU

EVGA/NVIDIA GeForce GTX 1060 3GB

### Additional information

![2023-05-24_10 12 24](https://github.com/SteamworkMC/Seaborgium/assets/42302831/1044e563-ed48-4430-a21d-124f423c44b6)

**Comment by UndefinedBHVR** [comment]
Finally have a chance to look at this, InventoryHUD+ is not open source, so I can't really do compatibility though seaborgium without decompiling their mod which is a huge taboo. 

If you can get the mod developer to reach out, I'd be able to work something out, but for now it's not really up to me to resolve.
