### ISSUE TITLE
1.20 wen?

### ISSUE THREAD

**Issue by VenomousReaperGoat** [SteamworkMC/Seaborgium#22]
### What feature?

Update...

### Give us more details.

ples 1.20!

**Comment by UndefinedBHVR** [comment]
Sorry, I haven't had time to work on this mod for a while due to irl work stuff. I'll be porting to 1.20 once I resolve #18 and #20

**Comment by VenomousReaperGoat** [comment]
Welp, thats unfortunate...  Hope everythings going well for you.

**Comment by UndefinedBHVR** [comment]
Bringing to 1.20 now, will make it work bare minimum again
