### ISSUE TITLE
Why was the mod removed off modrinth?

### ISSUE THREAD

**Issue by skibidibada** [SteamworkMC/Seaborgium#23]

**Comment by NovaAndrom3da** [comment]
I'm curious about the same thing. I'd like to use the mod again.

**Comment by Moonyol** [comment]
same

> I'm curious about the same thing. I'd like to use the mod again.

**Comment by roboboredom** [comment]
Bump

**Comment by mateus3c** [comment]
is there any way to download seaborgium now?

**Comment by UndefinedBHVR** [comment]
The mod is currently unmaintained as I haven't had time with work and such to update it. Once work slows down, I'll be able to look into updating it again and maintaining it, but for now it's basically abandoned. 

I had advertisements enabled on the page and it would feel wrong for me to earn money from something that its abandoned.

**Comment by Trickster-4** [comment]
> The mod is currently unmaintained as I haven't had time with work and such to update it. Once work slows down, I'll be able to look into updating it again and maintaining it, but for now it's basically abandoned.
> 
> I had advertisements enabled on the page and it would feel wrong for me to earn money from something that its abandoned.

that's a shame, even though the mod is unmantained it saved my ass as an AMD user. it was the first mod to feature optmizations for AMD machines and i got some boost from it.

gladly I had saved the mod in my PC.

**Comment by Phoenix-Starlight** [comment]
> The mod is currently unmaintained as I haven't had time with work and such to update it. Once work slows down, I'll be able to look into updating it again and maintaining it, but for now it's basically abandoned.
> 
> I had advertisements enabled on the page and it would feel wrong for me to earn money from something that its abandoned.

Hi, I am wondering whether I can maintain this mod, and post it to Modrinth again. You'll be listed on the page and will have your split currently at 0%, as you said yourself. Once you're back we can discuss the split again. You can see my fork (that has rewritten quite a lot of history to straighten stuff out) as it is now.

**Comment by Phoenix-Starlight** [comment]
Update: I realized the license is ARR. Is it okay to relicense as well?
Edit: Appears the mod metadata license is mistakenly ARR while repository is ISC.
