### ISSUE TITLE
[Bug]: Not compatible with Iris 1.6.5 on 1.19.4

### ISSUE THREAD

**Issue by will258012** [SteamworkMC/Seaborgium#24]
### Version information

seaborgium-mc1.19.4-0.1.3

### Expected Behavior

The game should starts normally.

### Actual Behavior

The game crashes at startup.
Working normally with Iris 1.6.4.

### Reproduction Steps

I only installed Fabric 0.14.22,Fabric API 0.86.1,Iris 1.6.5,sodium 0.4.10 and Seaborgium. 

### Java version

Java 20.0.2

### CPU

AMD Ryzen 5 5600H with Radeon Graphics  

### GPU

NVIDIA GeForce RTX 3050 Laptop GPU

### Additional information

[latest.log](https://github.com/SteamworkMC/Seaborgium/files/12328807/latest.log)
[crash-2023-08-13_12.24.37-client.txt](https://github.com/SteamworkMC/Seaborgium/files/12328808/crash-2023-08-13_12.24.37-client.txt)
[1.19.4.json.txt](https://github.com/SteamworkMC/Seaborgium/files/12328809/1.19.4.json.txt)

**Comment by bonkmaykr** [comment]
I was also able to reproduce this issue.

**Comment by UndefinedBHVR** [comment]
Looks like Iris changed a function I was using for my compatibility layer making the mixin no longer valid.
