### ISSUE TITLE
Hello i almost forgot about this mod 

### ISSUE THREAD

**Issue by Perez-Mark** [SteamworkMC/Seaborgium#25]
### What feature?

update to 1.20+

### Give us more details.

hello i been using this mod when  i saw it in the modrith website but its gone and didnt know where it was. I finally remembered the name and saw this github would you plss update the mod so i can use it again its really good

**Comment by Phoenix-Starlight** [comment]
See #23 and #22

**Comment by UndefinedBHVR** [comment]
This mod hasn't been relevant since roughly July, they implemented a similar cache system into Sodium.
