### ISSUE TITLE
[Question] Performance Improvement with ImmediatelyFast

### ISSUE THREAD

**Issue by R00tB33rMan** [SteamworkMC/Seaborgium#6]
ImmediatelyFast optimizes various things, like GUI elements (similarly to what Seaborgium does). I've been doing some testing and assume there is a marginal performance improvement. Could I be wrong and would pairing this with ImmediatelyFast improve client-sided performance?

**Comment by UndefinedBHVR** [comment]
There should still be some performance benefit when using Seaborgium with ImmediatelyFast. To my knowledge, Seaborgium and ImmediatelyFast have no overlapping patches. Though do note the benefits will likely be smaller with ImmediatelyFast on.

**Comment by Zorklis** [comment]
While compatible with Exordium, do this and that one compliment each other or would Exordium not be necessary

**Comment by UndefinedBHVR** [comment]
> While compatible with Exordium, do this and that one compliment each other or would Exordium not be necessary

I would encourage use of both together. Exordium primarily affects how often the GUI is allowed to be rendered and would also benefit from Seaborgium's uniform location cache.

**Comment by R00tB33rMan** [comment]
Really appreciate this response. I wasn't entirely sure, based on the noted details regarding Seaborgium and its improvements overall. Glad to see that it offers additional enhancements, outside of IF and Exordium. I do notice a marginal enhancement with Exordium + ImmediatelyFast by about ~2-3%!
