### ISSUE TITLE
[Question/Request] 1.19.2/1.18.2 Backport

### ISSUE THREAD

**Issue by ghost** [SteamworkMC/Seaborgium#9]
Are you considering backporting the mod to 1.19.2 and 1.18.2? There are modpacks which still use these versions (and I'm stuck on one of them), and could benefit from the performance this mod gives.

(p.s. Mod helps my fps plentiful with a bunch of utility mods so thank you :D)

**Comment by UndefinedBHVR** [comment]
It should be possible to backport, yes. I'll go ahead and add that to my task list.

**Comment by UndefinedBHVR** [comment]
According to my `mods.toml` and `fabric.mod.json`, 0.1.2 should already run on 1.19.2.

**Comment by UndefinedBHVR** [comment]
Correction, the titlescreen mixin I use does not work with 1.19.2. Apologies. I'll go ahead and fix this.

**Comment by ghost** [comment]
Nice, 1.18.2 version, thank you! Adding this to my pack :P
Keeping this issue open though until 1.19.2 is up and functional.

**Comment by UndefinedBHVR** [comment]
New version posted (pulled the original 0.1.3 due to an issue) should now work with 1.19.2

**Comment by ghost** [comment]
Actually, I'm getting an error with 1.18.2 on forge.
``
[18:54:54] [main/ERROR] [ne.mi.fm.lo.LanguageLoadingProvider/LOADING]: Missing language javafml version [43,) wanted by seaborgium-mc1.18.2-0.1.3.jar, found 40
``

**Comment by UndefinedBHVR** [comment]
Woops! Let me fix that.

**Comment by ghost** [comment]
> Woops! Let me fix that.

lol, it's okay. I sense the pain of being a java dev. Thanks btw for a quick response

**Comment by UndefinedBHVR** [comment]
Forge is a litttttle tad bit of a chore to deal with cause of mods.toml yeah

**Comment by ghost** [comment]
> Forge is a litttttle tad bit of a chore to deal with cause of mods.toml yeah

Wouldn't really know the experience as I use quilt/fabric most of the time, the modpack I'm playing right now is just forge tho.

**Comment by UndefinedBHVR** [comment]
Check the latest version and let me know

**Comment by ghost** [comment]
> Check the latest version and let me know

Same error, you sure you uploaded the new build? The jar offered on Modrinth is named the same as the broken build.

**Comment by ghost** [comment]
@UndefinedBHVR

**Comment by UndefinedBHVR** [comment]
> > Check the latest version and let me know
> 
> Same error, you sure you uploaded the new build? The jar offered on Modrinth is named the same as the broken build.

Ah they ask for FML in two spots in the mods.toml.
Forge is a pain haha

[0.1.3b](https://modrinth.com/mod/seaborgium/version/0.1.3b+1.18.2) should have that resolved now

**Comment by ghost** [comment]
Ah, that was problem lol. Okay the game loads up now on forge, not seeing any problems at all (even with shaders).
Getting a good 50 fps extra with the mod installed, thanks!

**Comment by UndefinedBHVR** [comment]
Thanks for letting me know.
